# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: |
          ${{ secrets.AERON_PYTHON_DEPLOY_KEY }}
          ${{ secrets.CCXTPRO_DEPLOY_KEY }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Aeron
      run: |
        git clone --branch 1.39.0 --depth 1 https://github.com/real-logic/aeron.git
        mkdir --parents aeron/cppbuild/Debug
        cd aeron/cppbuild/Debug
        cmake -DCMAKE_BUILD_TYPE=Debug ../..
        cmake --build . --clean-first --parallel 2
        sudo cmake --install .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Detection of Security Vulnerabilities
      run: pipenv check

    - name: Lint with Black
      uses: psf/black@stable
      with:
        src: "./flash_gate"

    - name: Test with pytest
      run: pipenv run pytest
